### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by JonathanImperato** [alejandroliu/pmimporter#1]

**Comment by alejandroliu** [comment]
Corrupted map

**Comment by Heromine** [comment]
It is not.
I can play it from PE

**Comment by alejandroliu** [comment]
What version of PE?

**Comment by Heromine** [comment]
Like the Previous message says, 0.11

**Comment by alejandroliu** [comment]
OMG,  did you read the documentation?  It clearly states:

It supports the following input formats:
- McRegion (Minecraft PC Edition, PocketMine v1.4)
- Anvil (Minecraft PC Edition)
- PMF (PocketMine v1.3)
- mcpe020 (Minecraft PE 0.2.0-0.8.1)

**Comment by Heromine** [comment]
Yes i did xD
